const $=id=>document.getElementById(id);const auth=$('auth'),app=$('app'),authMsg=$('authMsg');let meUser=null,projects=[];
function msg(el,text,ok=false){el.textContent=text;el.style.color=ok?'#71e3a4':'#ff9ca8'}
async function api(path,opts={}){const r=await fetch(path,{credentials:'same-origin',...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
$('showSignup').onclick=()=>{$('loginForm').classList.add('hidden');$('signupForm').classList.remove('hidden');authMsg.textContent=''};
$('showLogin').onclick=()=>{$('signupForm').classList.add('hidden');$('loginForm').classList.remove('hidden');authMsg.textContent=''};
$('loginBtn').onclick=async()=>{try{const d=await api('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});enter(d.user)}catch(e){msg(authMsg,e.message)}};
$('signupBtn').onclick=async()=>{try{const d=await api('/api/auth/signup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:$('signupName').value,email:$('signupEmail').value,password:$('signupPassword').value})});enter(d.user)}catch(e){msg(authMsg,e.message)}};
$('profileBtn').onclick=async()=>{if(confirm('Log out of Legend Host?')){await api('/api/auth/logout',{method:'POST'});location.reload()}};
function enter(u){meUser=u;auth.classList.add('hidden');app.classList.remove('hidden');$('welcome').textContent=`Welcome, ${u.name} 👋`;$('profileBtn').textContent=(u.name[0]||'U').toUpperCase();loadProjects()}
async function loadProjects(){try{const d=await api('/api/projects');projects=d.projects||[];renderProjects()}catch(e){console.error(e)}}
function renderProjects(){ $('projectCount').textContent=projects.length;$('liveCount').textContent=projects.filter(p=>p.status==='live').length;$('deploymentCount').textContent=projects.filter(p=>p.status==='live'||p.status==='deploying').length;const list=$('projectList');$('empty').classList.toggle('hidden',projects.length>0);list.innerHTML=projects.map(p=>`<div class="project"><div><b>${esc(p.name)}</b><small>${esc(p.status)} · ${esc(p.source_type)}</small></div><div class="actions">${p.url?`<a href="${esc(p.url)}" target="_blank" rel="noopener">Open</a>`:''}<button class="danger" data-delete="${p.id}">Delete</button></div></div>`).join('');list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this project and its hosting project?'))return;try{await api('/api/projects/'+b.dataset.delete,{method:'DELETE'});loadProjects()}catch(e){alert(e.message)}})}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const modal=$('modal');function openModal(){modal.classList.add('show');$('status').textContent='';$('projectName').value=''}function closeModal(){modal.classList.remove('show')};$('newProject').onclick=openModal;$('emptyNew').onclick=openModal;$('upload').onclick=openModal;$('close').onclick=closeModal;
$('zipChoice').onclick=async()=>{const name=$('projectName').value.trim();if(name.length<2){msg($('status'),'Enter a project name first.');return}$('file').click()};
$('file').onchange=async()=>{const zip=$('file').files[0];if(!zip)return;const name=$('projectName').value.trim();try{msg($('status'),'Reading ZIP…',true);const extracted=await unzip(zip);if(!extracted.some(x=>x.path.toLowerCase()==='index.html'))throw new Error('index.html must be in the ZIP root.');const created=await api('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,source_type:'upload'})});msg($('status'),`Uploading ${extracted.length} files…`,true);const fd=new FormData();fd.append('project_id',created.project.id);fd.append('manifest',JSON.stringify({files:extracted.map(x=>({path:x.path,size:x.file.size,type:x.file.type}))}));extracted.forEach((x,i)=>fd.append(`file_${i}`,x.file,x.path));const r=await fetch('/api/deployments',{method:'POST',body:fd,credentials:'same-origin'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Deployment failed');msg($('status'),`Live: ${d.url}`,true);await loadProjects();setTimeout(closeModal,1200)}catch(e){msg($('status'),e.message)}};
async function unzip(blob){if(blob.size>20*1024*1024)throw new Error('ZIP maximum is 20 MB.');const b=new Uint8Array(await blob.arrayBuffer());const dv=new DataView(b.buffer);let eocd=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error('Invalid ZIP file.');const entries=dv.getUint16(eocd+10,true),cdSize=dv.getUint32(eocd+12,true),cdOff=dv.getUint32(eocd+16,true);if(entries>1000||cdOff+cdSize>b.length)throw new Error('ZIP is too large or ZIP64 is not supported.');let p=cdOff,total=0,out=[];for(let n=0;n<entries;n++){if(dv.getUint32(p,true)!==0x02014b50)throw new Error('Invalid ZIP directory.');const method=dv.getUint16(p+10,true),csize=dv.getUint32(p+20,true),usize=dv.getUint32(p+24,true),nl=dv.getUint16(p+28,true),xl=dv.getUint16(p+30,true),cl=dv.getUint16(p+32,true),lh=dv.getUint32(p+42,true);const nameBytes=b.slice(p+46,p+46+nl);const name=new TextDecoder().decode(nameBytes);p+=46+nl+xl+cl;if(!name||name.endsWith('/'))continue;if(name.includes('..')||name.startsWith('/')||name.includes('\\'))throw new Error('Unsafe ZIP path.');if(usize>25*1024*1024)throw new Error(`File too large: ${name}`);total+=usize;if(total>60*1024*1024)throw new Error('Extracted website is too large.');if(dv.getUint32(lh,true)!==0x04034b50)throw new Error('Invalid ZIP entry.');const lnl=dv.getUint16(lh+26,true),lxl=dv.getUint16(lh+28,true),start=lh+30+lnl+lxl,raw=b.slice(start,start+csize);let data;if(method===0)data=raw;else if(method===8){if(!('DecompressionStream' in window))throw new Error('This browser does not support ZIP deflate extraction.');const ds=new DecompressionStream('deflate-raw');data=new Uint8Array(await new Response(new Blob([raw]).stream().pipeThrough(ds)).arrayBuffer())}else throw new Error(`Unsupported ZIP compression in ${name}`);if(data.length!==usize)throw new Error(`ZIP size mismatch: ${name}`);out.push({path:name,file:new File([data],name,{type:mime(name)})})}return out}
function mime(path){const x=path.toLowerCase().split('.').pop();return ({html:'text/html',css:'text/css',js:'application/javascript',json:'application/json',svg:'image/svg+xml',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',ico:'image/x-icon',txt:'text/plain',xml:'application/xml',woff:'font/woff',woff2:'font/woff2'})[x]||'application/octet-stream'}
const ghModal=$('githubModal');$('githubChoice').onclick=()=>{closeModal();ghModal.classList.add('show');loadRepos()};$('githubClose').onclick=()=>ghModal.classList.remove('show');$('connectGithub').onclick=()=>location.href='/api/github/start';
async function loadRepos(){try{const d=await api('/api/github/repos');$('connectGithub').classList.add('hidden');$('repoSelect').classList.remove('hidden');$('repoSelect').innerHTML=d.repositories.map(r=>`<option value="${r.id}" data-name="${esc(r.name)}" data-branch="${esc(r.default_branch)}">${esc(r.name)}${r.private?' 🔒':''}</option>`).join('');$('deployGithub').classList.remove('hidden')}catch(e){$('ghText').textContent='Connect GitHub to import a repository.';$('ghStatus').textContent=e.message}};
$('deployGithub').onclick=async()=>{try{const o=$('repoSelect').selectedOptions[0];const name=o.dataset.name.split('/').pop();const d=await api('/api/github/deploy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,repo_id:o.value,repo_name:o.dataset.name,branch:o.dataset.branch})});msg($('ghStatus'),'GitHub deployment configured.',true);await loadProjects()}catch(e){msg($('ghStatus'),e.message)}};
(async()=>{try{const d=await api('/api/auth/me');if(d.user)enter(d.user)}catch{}})();
