name = "legend-host"
main = "src/index.js"
compatibility_date = "2026-09-24"

[assets]
directory = "../frontend"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "legend-host"
database_id = "0403cdc3-0180-42b1-9e28-60338981b2c8"

# Optional secrets:
# CLOUDFLARE_API_TOKEN
# CLOUDFLARE_ACCOUNT_ID
# GITHUB_CLIENT_ID
# GITHUB_CLIENT_SECRET
# GITHUB_REDIRECT_URI
# APP_ORIGIN
# APP_ENCRYPTION_KEY
